# Generated by Django 4.2.16 on 2024-11-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registerCode',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
